### ISSUE TITLE
add_stat effect not working with aurelium skills

### ISSUE THREAD

**Issue by Wall0fFlesh** [Auxilor/Reforges#10]
Hello

I made a reforge that gives you 10 strength when applied to any diamond item, but when i held my reforged diamond sword, it gave me an error

[17:39:48 WARN]: [Reforges] Task #33126 for Reforges v4.11.2 generated an exception
java.lang.IllegalArgumentException: No enum constant com.archyx.aureliumskills.stats.Stats.strength
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at com.archyx.aureliumskills.stats.Stats.valueOf(Stats.java:8) ~[AureliumSkills-Beta1.2.7.jar:?]
        at com.willfp.reforges.libreforge.integrations.aureliumskills.EffectAddStat.handleEnable(EffectAddStat.kt:18) ~[Reforges v4.11.2.jar:?]
        at com.willfp.reforges.libreforge.effects.Effect.enableForPlayer(Effect.kt:101) ~[Reforges v4.11.2.jar:?]
        at com.willfp.reforges.libreforge.LibReforgeUtils.updateEffects(LibReforge.kt:177) ~[Reforges v4.11.2.jar:?]
        at com.willfp.reforges.reforges.util.ReforgeEnableListeners.refreshPlayer(ReforgeEnableListeners.java:139) ~[Reforges v4.11.2.jar:?]
        at com.willfp.reforges.reforges.util.ReforgeEnableListeners.lambda$onChangeSlot$0(ReforgeEnableListeners.java:101) ~[Reforges v4.11.2.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-400]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-400]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-400]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-400]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-400]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-400]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-400]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

Im playing on 1.17.1 and im using Paper 1.17.1 to run my server, im also using Java 17

Can you help me please? Thanks

**Comment by i1470s** [comment]
i have the same issue on 1.20.6 any chance you figured it out?
